import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "@/components/Navbar";
import AuthProvider from "@/components/SessionProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <AuthProvider>
          <header>
            <Navbar />
          </header>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
